// Code generated by govalid; DO NOT EDIT.
package minlength

import (
	"errors"
	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMinLength is returned when the MinLength is nil.
	ErrNilMinLength = errors.New("input MinLength is nil")

	// ErrMinLengthStringMinLengthValidation is the error returned when the length of the field is less than the minimum of 5.
	ErrMinLengthStringMinLengthValidation = govaliderrors.ValidationError{Reason: "field String must have a minimum length of 5", Path: "MinLength.String", Type: "minlength"}

	// Deprecated: Use ErrMinLengthStructNameMinLengthValidation
	//
	// ErrMinLengthNameMinLengthValidation is deprecated and is kept for compatibility purpose.
	ErrMinLengthNameMinLengthValidation = ErrMinLengthStructNameMinLengthValidation

	// ErrMinLengthStructNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrMinLengthStructNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a minimum length of 3", Path: "MinLength.Struct.Name", Type: "minlength"}
)

func ValidateMinLength(t *MinLength) error {
	if t == nil {
		return ErrNilMinLength
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.String) < 5 {
		err := ErrMinLengthStringMinLengthValidation
		err.Value = t.String
		errs = append(errs, err)
	}

	{
		t := t.Struct

		if utf8.RuneCountInString(t.Name) < 3 {
			err := ErrMinLengthStructNameMinLengthValidation
			err.Value = t.Name
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MinLength)(nil)

func (t *MinLength) Validate() error {
	return ValidateMinLength(t)
}
