// Code generated by generate-validators; DO NOT EDIT.
package markers

var (
	// GoValidMarkerAlpha is the marker for alpha validation.
	GoValidMarkerAlpha = "govalid:alpha"

	// GoValidMarkerAlphanum is the marker for alphanum validation.
	GoValidMarkerAlphanum = "govalid:alphanum"

	// GoValidMarkerBoolean is the marker for boolean validation.
	GoValidMarkerBoolean = "govalid:boolean"

	// GoValidMarkerCel is the marker for cel validation.
	GoValidMarkerCel = "govalid:cel"

	// GoValidMarkerContainsany is the marker for containsany validation.
	GoValidMarkerContainsany = "govalid:containsany"

	// GoValidMarkerDate is the marker for date validation.
	GoValidMarkerDate = "govalid:date"

	// GoValidMarkerEmail is the marker for email validation.
	GoValidMarkerEmail = "govalid:email"

	// GoValidMarkerEnum is the marker for enum validation.
	GoValidMarkerEnum = "govalid:enum"

	// GoValidMarkerEq is the marker for eq validation.
	GoValidMarkerEq = "govalid:eq"

	// GoValidMarkerExcluded_if is the marker for excluded_if validation.
	GoValidMarkerExcluded_if = "govalid:excluded_if"

	// GoValidMarkerExcluded_unless is the marker for excluded_unless validation.
	GoValidMarkerExcluded_unless = "govalid:excluded_unless"

	// GoValidMarkerExcluded_with is the marker for excluded_with validation.
	GoValidMarkerExcluded_with = "govalid:excluded_with"

	// GoValidMarkerExcluded_with_all is the marker for excluded_with_all validation.
	GoValidMarkerExcluded_with_all = "govalid:excluded_with_all"

	// GoValidMarkerExcluded_without is the marker for excluded_without validation.
	GoValidMarkerExcluded_without = "govalid:excluded_without"

	// GoValidMarkerExcluded_without_all is the marker for excluded_without_all validation.
	GoValidMarkerExcluded_without_all = "govalid:excluded_without_all"

	// GoValidMarkerExcludes is the marker for excludes validation.
	GoValidMarkerExcludes = "govalid:excludes"

	// GoValidMarkerExcludesall is the marker for excludesall validation.
	GoValidMarkerExcludesall = "govalid:excludesall"

	// GoValidMarkerFqdn is the marker for fqdn validation.
	GoValidMarkerFqdn = "govalid:fqdn"

	// GoValidMarkerGt is the marker for gt validation.
	GoValidMarkerGt = "govalid:gt"

	// GoValidMarkerGte is the marker for gte validation.
	GoValidMarkerGte = "govalid:gte"

	// GoValidMarkerIpv4 is the marker for ipv4 validation.
	GoValidMarkerIpv4 = "govalid:ipv4"

	// GoValidMarkerIpv6 is the marker for ipv6 validation.
	GoValidMarkerIpv6 = "govalid:ipv6"

	// GoValidMarkerIscolour is the marker for iscolour validation.
	GoValidMarkerIscolour = "govalid:iscolour"

	// GoValidMarkerIsdefault is the marker for isdefault validation.
	GoValidMarkerIsdefault = "govalid:isdefault"

	// GoValidMarkerLatitude is the marker for latitude validation.
	GoValidMarkerLatitude = "govalid:latitude"

	// GoValidMarkerLength is the marker for length validation.
	GoValidMarkerLength = "govalid:length"

	// GoValidMarkerLongitude is the marker for longitude validation.
	GoValidMarkerLongitude = "govalid:longitude"

	// GoValidMarkerLowercase is the marker for lowercase validation.
	GoValidMarkerLowercase = "govalid:lowercase"

	// GoValidMarkerLt is the marker for lt validation.
	GoValidMarkerLt = "govalid:lt"

	// GoValidMarkerLte is the marker for lte validation.
	GoValidMarkerLte = "govalid:lte"

	// GoValidMarkerMaxduration is the marker for maxduration validation.
	GoValidMarkerMaxduration = "govalid:maxduration"

	// GoValidMarkerMaxitems is the marker for maxitems validation.
	GoValidMarkerMaxitems = "govalid:maxitems"

	// GoValidMarkerMaxlength is the marker for maxlength validation.
	GoValidMarkerMaxlength = "govalid:maxlength"

	// GoValidMarkerMin is the marker for min validation.
	GoValidMarkerMin = "govalid:min"

	// GoValidMarkerMinduration is the marker for minduration validation.
	GoValidMarkerMinduration = "govalid:minduration"

	// GoValidMarkerMinitems is the marker for minitems validation.
	GoValidMarkerMinitems = "govalid:minitems"

	// GoValidMarkerMinlength is the marker for minlength validation.
	GoValidMarkerMinlength = "govalid:minlength"

	// GoValidMarkerNe is the marker for ne validation.
	GoValidMarkerNe = "govalid:ne"

	// GoValidMarkerNumber is the marker for number validation.
	GoValidMarkerNumber = "govalid:number"

	// GoValidMarkerNumeric is the marker for numeric validation.
	GoValidMarkerNumeric = "govalid:numeric"

	// GoValidMarkerOneof is the marker for oneof validation.
	GoValidMarkerOneof = "govalid:oneof"

	// GoValidMarkerRequired is the marker for required validation.
	GoValidMarkerRequired = "govalid:required"

	// GoValidMarkerRequired_if is the marker for required_if validation.
	GoValidMarkerRequired_if = "govalid:required_if"

	// GoValidMarkerRequired_unless is the marker for required_unless validation.
	GoValidMarkerRequired_unless = "govalid:required_unless"

	// GoValidMarkerRequired_with is the marker for required_with validation.
	GoValidMarkerRequired_with = "govalid:required_with"

	// GoValidMarkerRequired_with_all is the marker for required_with_all validation.
	GoValidMarkerRequired_with_all = "govalid:required_with_all"

	// GoValidMarkerRequired_without is the marker for required_without validation.
	GoValidMarkerRequired_without = "govalid:required_without"

	// GoValidMarkerRequired_without_all is the marker for required_without_all validation.
	GoValidMarkerRequired_without_all = "govalid:required_without_all"

	// GoValidMarkerUnique is the marker for unique validation.
	GoValidMarkerUnique = "govalid:unique"

	// GoValidMarkerUri is the marker for uri validation.
	GoValidMarkerUri = "govalid:uri"

	// GoValidMarkerUrl is the marker for url validation.
	GoValidMarkerUrl = "govalid:url"

	// GoValidMarkerUuid is the marker for uuid validation.
	GoValidMarkerUuid = "govalid:uuid"

)

// GoValidMarkers is a map of valid govalid markers.
var GoValidMarkers = map[string]struct{}{
	GoValidMarkerAlpha: {},
	GoValidMarkerAlphanum: {},
	GoValidMarkerBoolean: {},
	GoValidMarkerCel: {},
	GoValidMarkerContainsany: {},
	GoValidMarkerDate: {},
	GoValidMarkerEmail: {},
	GoValidMarkerEnum: {},
	GoValidMarkerEq: {},
	GoValidMarkerExcluded_if: {},
	GoValidMarkerExcluded_unless: {},
	GoValidMarkerExcluded_with: {},
	GoValidMarkerExcluded_with_all: {},
	GoValidMarkerExcluded_without: {},
	GoValidMarkerExcluded_without_all: {},
	GoValidMarkerExcludes: {},
	GoValidMarkerExcludesall: {},
	GoValidMarkerFqdn: {},
	GoValidMarkerGt: {},
	GoValidMarkerGte: {},
	GoValidMarkerIpv4: {},
	GoValidMarkerIpv6: {},
	GoValidMarkerIscolour: {},
	GoValidMarkerIsdefault: {},
	GoValidMarkerLatitude: {},
	GoValidMarkerLength: {},
	GoValidMarkerLongitude: {},
	GoValidMarkerLowercase: {},
	GoValidMarkerLt: {},
	GoValidMarkerLte: {},
	GoValidMarkerMaxduration: {},
	GoValidMarkerMaxitems: {},
	GoValidMarkerMaxlength: {},
	GoValidMarkerMin: {},
	GoValidMarkerMinduration: {},
	GoValidMarkerMinitems: {},
	GoValidMarkerMinlength: {},
	GoValidMarkerNe: {},
	GoValidMarkerNumber: {},
	GoValidMarkerNumeric: {},
	GoValidMarkerOneof: {},
	GoValidMarkerRequired: {},
	GoValidMarkerRequired_if: {},
	GoValidMarkerRequired_unless: {},
	GoValidMarkerRequired_with: {},
	GoValidMarkerRequired_with_all: {},
	GoValidMarkerRequired_without: {},
	GoValidMarkerRequired_without_all: {},
	GoValidMarkerUnique: {},
	GoValidMarkerUri: {},
	GoValidMarkerUrl: {},
	GoValidMarkerUuid: {},
}
