// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilExcludedIf is returned when the ExcludedIf is nil.
	ErrNilExcludedIf = errors.New("input ExcludedIf is nil")

	// ErrExcludedIfInactiveFieldExcludedIfValidation is the error returned when the field must be absent due to another field's value.
	ErrExcludedIfInactiveFieldExcludedIfValidation = govaliderrors.ValidationError{Reason: "inactive_field must be absent when Status equals \"inactive\"", Path: "inactive_field", Type: "excluded_if"}
)

func ValidateExcludedIf(t *ExcludedIf) error {
	if t == nil {
		return ErrNilExcludedIf
	}

	var errs govaliderrors.ValidationErrors

	if t.Status == "inactive" && t.InactiveField != "" {
		err := ErrExcludedIfInactiveFieldExcludedIfValidation
		err.Value = t.InactiveField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludedIf)(nil)

func (t *ExcludedIf) Validate() error {
	return ValidateExcludedIf(t)
}
