// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilNe is returned when the Ne is nil.
	ErrNilNe = errors.New("input Ne is nil")

	// ErrNeRoleNeValidation is the error returned when the field equals \"admin\" but should not.
	ErrNeRoleNeValidation = govaliderrors.ValidationError{Reason: "field Role must not equal \"admin\"", Path: "Ne.Role", Type: "ne"}

	// ErrNeScoreNeValidation is the error returned when the field equals 0 but should not.
	ErrNeScoreNeValidation = govaliderrors.ValidationError{Reason: "field Score must not equal 0", Path: "Ne.Score", Type: "ne"}
)

func ValidateNe(t *Ne) error {
	if t == nil {
		return ErrNilNe
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Role != "admin") {
		err := ErrNeRoleNeValidation
		err.Value = t.Role
		errs = append(errs, err)
	}

	if !(t.Score != 0) {
		err := ErrNeScoreNeValidation
		err.Value = t.Score
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Ne)(nil)

func (t *Ne) Validate() error {
	return ValidateNe(t)
}
