// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilRequiredWith is returned when the RequiredWith is nil.
	ErrNilRequiredWith = errors.New("input RequiredWith is nil")

	// ErrRequiredWithEmailConfirmationRequiredWithValidation is the error returned when the field is required because other fields are present.
	ErrRequiredWithEmailConfirmationRequiredWithValidation = govaliderrors.ValidationError{Reason: "field EmailConfirmation is required when any of Email are present", Path: "RequiredWith.EmailConfirmation", Type: "required_with"}
)

func ValidateRequiredWith(t *RequiredWith) error {
	if t == nil {
		return ErrNilRequiredWith
	}

	var errs govaliderrors.ValidationErrors

	if (t.Email != "") && t.EmailConfirmation == "" {
		err := ErrRequiredWithEmailConfirmationRequiredWithValidation
		err.Value = t.EmailConfirmation
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequiredWith)(nil)

func (t *RequiredWith) Validate() error {
	return ValidateRequiredWith(t)
}
