// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGTE is returned when the GTE is nil.
	ErrNilGTE = errors.New("input GTE is nil")

	// ErrGTEAgeGTEValidation is the error returned when the value of the field is less than 18.
	ErrGTEAgeGTEValidation = govaliderrors.ValidationError{Reason: "field Age must be greater than or equal to 18", Path: "GTE.Age", Type: "gte"}
)

func ValidateGTE(t *GTE) error {
	if t == nil {
		return ErrNilGTE
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age >= 18) {
		err := ErrGTEAgeGTEValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GTE)(nil)

func (t *GTE) Validate() error {
	return ValidateGTE(t)
}
