// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilLongitude is returned when the Longitude is nil.
	ErrNilLongitude = errors.New("input Longitude is nil")

	// ErrLongitudeLonLongitudeValidation is the error returned when the field is not a valid longitude (-180 to 180).
	ErrLongitudeLonLongitudeValidation = govaliderrors.ValidationError{Reason: "field Lon must be a valid longitude (-180 to 180)", Path: "Longitude.Lon", Type: "longitude"}
)

func ValidateLongitude(t *Longitude) error {
	if t == nil {
		return ErrNilLongitude
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidLongitude(t.Lon) {
		err := ErrLongitudeLonLongitudeValidation
		err.Value = t.Lon
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Longitude)(nil)

func (t *Longitude) Validate() error {
	return ValidateLongitude(t)
}
