// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"time"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMinDuration is returned when the MinDuration is nil.
	ErrNilMinDuration = errors.New("input MinDuration is nil")

	// ErrMinDurationTimeoutMindurationValidation is the error returned when the duration is less than the minimum.
	ErrMinDurationTimeoutMindurationValidation = govaliderrors.ValidationError{Reason: "field Timeout must be at least 1h", Path: "MinDuration.Timeout", Type: "minduration"}
)

func ValidateMinDuration(t *MinDuration) error {
	if t == nil {
		return ErrNilMinDuration
	}

	var errs govaliderrors.ValidationErrors

	if func() bool { d, _ := time.ParseDuration("1h"); return t.Timeout < d }() {
		err := ErrMinDurationTimeoutMindurationValidation
		err.Value = t.Timeout
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MinDuration)(nil)

func (t *MinDuration) Validate() error {
	return ValidateMinDuration(t)
}
