// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilURI is returned when the URI is nil.
	ErrNilURI = errors.New("input URI is nil")

	// ErrURIAddressURIValidation is the error returned when the field is not a URI.
	ErrURIAddressURIValidation = govaliderrors.ValidationError{Reason: "address must be a URI", Path: "address", Type: "uri"}
)

func ValidateURI(t *URI) error {
	if t == nil {
		return ErrNilURI
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidURI(t.Address) {
		err := ErrURIAddressURIValidation
		err.Value = t.Address
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*URI)(nil)

func (t *URI) Validate() error {
	return ValidateURI(t)
}
