// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilLatitude is returned when the Latitude is nil.
	ErrNilLatitude = errors.New("input Latitude is nil")

	// ErrLatitudeLatLatitudeValidation is the error returned when the field is not a valid latitude (-90 to 90).
	ErrLatitudeLatLatitudeValidation = govaliderrors.ValidationError{Reason: "field Lat must be a valid latitude (-90 to 90)", Path: "Latitude.Lat", Type: "latitude"}
)

func ValidateLatitude(t *Latitude) error {
	if t == nil {
		return ErrNilLatitude
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidLatitude(t.Lat) {
		err := ErrLatitudeLatLatitudeValidation
		err.Value = t.Lat
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Latitude)(nil)

func (t *Latitude) Validate() error {
	return ValidateLatitude(t)
}
