// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilEmail is returned when the Email is nil.
	ErrNilEmail = errors.New("input Email is nil")

	// ErrEmailEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrEmailEmailEmailValidation = govaliderrors.ValidationError{Reason: "email must be a valid email address", Path: "email", Type: "email"}
)

func ValidateEmail(t *Email) error {
	if t == nil {
		return ErrNilEmail
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrEmailEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Email)(nil)

func (t *Email) Validate() error {
	return ValidateEmail(t)
}
