// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilIsColour is returned when the IsColour is nil.
	ErrNilIsColour = errors.New("input IsColour is nil")

	// ErrIsColourColorIscolourValidation is the error returned when the field is not a valid color format.
	ErrIsColourColorIscolourValidation = govaliderrors.ValidationError{Reason: "color must be a valid color format", Path: "color", Type: "iscolour"}
)

func ValidateIsColour(t *IsColour) error {
	if t == nil {
		return ErrNilIsColour
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidColour(t.Color) {
		err := ErrIsColourColorIscolourValidation
		err.Value = t.Color
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*IsColour)(nil)

func (t *IsColour) Validate() error {
	return ValidateIsColour(t)
}
