// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilRequiredWithout is returned when the RequiredWithout is nil.
	ErrNilRequiredWithout = errors.New("input RequiredWithout is nil")

	// ErrRequiredWithoutEmailRequiredWithoutValidation is the error returned when the field is required because other fields are absent.
	ErrRequiredWithoutEmailRequiredWithoutValidation = govaliderrors.ValidationError{Reason: "field Email is required when any of Phone are absent", Path: "RequiredWithout.Email", Type: "required_without"}
)

func ValidateRequiredWithout(t *RequiredWithout) error {
	if t == nil {
		return ErrNilRequiredWithout
	}

	var errs govaliderrors.ValidationErrors

	if (t.Phone == "") && t.Email == "" {
		err := ErrRequiredWithoutEmailRequiredWithoutValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequiredWithout)(nil)

func (t *RequiredWithout) Validate() error {
	return ValidateRequiredWithout(t)
}
