// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilRequiredIf is returned when the RequiredIf is nil.
	ErrNilRequiredIf = errors.New("input RequiredIf is nil")

	// ErrRequiredIfActiveFieldRequiredIfValidation is the error returned when the field is required due to another field's value.
	ErrRequiredIfActiveFieldRequiredIfValidation = govaliderrors.ValidationError{Reason: "field ActiveField is required when Status equals \"active\"", Path: "RequiredIf.ActiveField", Type: "required_if"}
)

func ValidateRequiredIf(t *RequiredIf) error {
	if t == nil {
		return ErrNilRequiredIf
	}

	var errs govaliderrors.ValidationErrors

	if t.Status == "active" && t.ActiveField == "" {
		err := ErrRequiredIfActiveFieldRequiredIfValidation
		err.Value = t.ActiveField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequiredIf)(nil)

func (t *RequiredIf) Validate() error {
	return ValidateRequiredIf(t)
}
