// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"net"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilIPV4 is returned when the IPV4 is nil.
	ErrNilIPV4 = errors.New("input IPV4 is nil")

	// ErrIPV4IPIpv4Validation is returned when the IP fails ipv4 validation.
	ErrIPV4IPIpv4Validation = govaliderrors.ValidationError{Reason: "field IP failed ipv4 validation", Path: "IPV4.IP", Type: "ipv4"}
)

func ValidateIPV4(t *IPV4) error {
	if t == nil {
		return ErrNilIPV4
	}

	var errs govaliderrors.ValidationErrors

	if ip := net.ParseIP(t.IP); ip == nil || ip.To4() == nil {
		err := ErrIPV4IPIpv4Validation
		err.Value = t.IP
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*IPV4)(nil)

func (t *IPV4) Validate() error {
	return ValidateIPV4(t)
}
