// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"time"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMaxDuration is returned when the MaxDuration is nil.
	ErrNilMaxDuration = errors.New("input MaxDuration is nil")

	// ErrMaxDurationIntervalMaxdurationValidation is the error returned when the duration exceeds the maximum.
	ErrMaxDurationIntervalMaxdurationValidation = govaliderrors.ValidationError{Reason: "field Interval must not exceed 24h", Path: "MaxDuration.Interval", Type: "maxduration"}
)

func ValidateMaxDuration(t *MaxDuration) error {
	if t == nil {
		return ErrNilMaxDuration
	}

	var errs govaliderrors.ValidationErrors

	if func() bool { d, _ := time.ParseDuration("24h"); return t.Interval > d }() {
		err := ErrMaxDurationIntervalMaxdurationValidation
		err.Value = t.Interval
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MaxDuration)(nil)

func (t *MaxDuration) Validate() error {
	return ValidateMaxDuration(t)
}
