// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilURL is returned when the URL is nil.
	ErrNilURL = errors.New("input URL is nil")

	// ErrURLURLURLValidation is the error returned when the field is not a valid URL.
	ErrURLURLURLValidation = govaliderrors.ValidationError{Reason: "field URL must be a valid URL", Path: "URL.URL", Type: "url"}
)

func ValidateURL(t *URL) error {
	if t == nil {
		return ErrNilURL
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidURL(t.URL) {
		err := ErrURLURLURLValidation
		err.Value = t.URL
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*URL)(nil)

func (t *URL) Validate() error {
	return ValidateURL(t)
}
