// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMin is returned when the Min is nil.
	ErrNilMin = errors.New("input Min is nil")

	// ErrMinAgeMinValidation is the error returned when the value of the field is less than the minimum of 10.
	ErrMinAgeMinValidation = govaliderrors.ValidationError{Reason: "field Age must be greater than or equal to 10", Path: "Min.Age", Type: "min"}
)

func ValidateMin(t *Min) error {
	if t == nil {
		return ErrNilMin
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age >= 10) {
		err := ErrMinAgeMinValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Min)(nil)

func (t *Min) Validate() error {
	return ValidateMin(t)
}
