// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"strings"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilExcludes is returned when the Excludes is nil.
	ErrNilExcludes = errors.New("input Excludes is nil")

	// ErrExcludesUsernameExcludesValidation is the error returned when the field contains the excluded substring.
	ErrExcludesUsernameExcludesValidation = govaliderrors.ValidationError{Reason: "field Username must not contain: admin", Path: "Excludes.Username", Type: "excludes"}
)

func ValidateExcludes(t *Excludes) error {
	if t == nil {
		return ErrNilExcludes
	}

	var errs govaliderrors.ValidationErrors

	if strings.Contains(t.Username, "admin") {
		err := ErrExcludesUsernameExcludesValidation
		err.Value = t.Username
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Excludes)(nil)

func (t *Excludes) Validate() error {
	return ValidateExcludes(t)
}
