// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilBoolean is returned when the Boolean is nil.
	ErrNilBoolean = errors.New("input Boolean is nil")

	// ErrBooleanFlagBooleanValidation is the error returned when the field is not a valid boolean string.
	ErrBooleanFlagBooleanValidation = govaliderrors.ValidationError{Reason: "flag must be a valid boolean (true, false, 1, 0, yes, no, on, off)", Path: "flag", Type: "boolean"}
)

func ValidateBoolean(t *Boolean) error {
	if t == nil {
		return ErrNilBoolean
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidBoolean(t.Flag) {
		err := ErrBooleanFlagBooleanValidation
		err.Value = t.Flag
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Boolean)(nil)

func (t *Boolean) Validate() error {
	return ValidateBoolean(t)
}
