// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilNumber is returned when the Number is nil.
	ErrNilNumber = errors.New("input Number is nil")

	// ErrNumberNumericStringNumberValidation is the error returned when the field contains non-numeric characters.
	ErrNumberNumericStringNumberValidation = govaliderrors.ValidationError{Reason: "numeric_string must contain only numbers", Path: "numeric_string", Type: "number"}
)

func ValidateNumber(t *Number) error {
	if t == nil {
		return ErrNilNumber
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsNumber(t.NumericString) {
		err := ErrNumberNumericStringNumberValidation
		err.Value = t.NumericString
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Number)(nil)

func (t *Number) Validate() error {
	return ValidateNumber(t)
}
