// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilCELCrossField is returned when the CELCrossField is nil.
	ErrNilCELCrossField = errors.New("input CELCrossField is nil")

	// ErrCELCrossFieldPriceCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELCrossFieldPriceCELValidation = govaliderrors.ValidationError{Reason: "price failed CEL validation: value < this.MaxPrice", Path: "price", Type: "cel"}

	// ErrCELCrossFieldQuantityCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELCrossFieldQuantityCELValidation = govaliderrors.ValidationError{Reason: "quantity failed CEL validation: value * this.Price <= this.Budget", Path: "quantity", Type: "cel"}
)

func ValidateCELCrossField(t *CELCrossField) error {
	if t == nil {
		return ErrNilCELCrossField
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Price < t.MaxPrice) {
		err := ErrCELCrossFieldPriceCELValidation
		err.Value = t.Price
		errs = append(errs, err)
	}

	if !(t.Quantity*t.Price <= t.Budget) {
		err := ErrCELCrossFieldQuantityCELValidation
		err.Value = t.Quantity
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CELCrossField)(nil)

func (t *CELCrossField) Validate() error {
	return ValidateCELCrossField(t)
}
