// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilRequiredWithoutAll is returned when the RequiredWithoutAll is nil.
	ErrNilRequiredWithoutAll = errors.New("input RequiredWithoutAll is nil")

	// ErrRequiredWithoutAllEmailRequiredWithoutAllValidation is the error returned when the field is required because all other fields are absent.
	ErrRequiredWithoutAllEmailRequiredWithoutAllValidation = govaliderrors.ValidationError{Reason: "email is required when all of Phone, Fax are absent", Path: "email", Type: "required_without_all"}
)

func ValidateRequiredWithoutAll(t *RequiredWithoutAll) error {
	if t == nil {
		return ErrNilRequiredWithoutAll
	}

	var errs govaliderrors.ValidationErrors

	if (t.Phone == "" && t.Fax == "") && t.Email == "" {
		err := ErrRequiredWithoutAllEmailRequiredWithoutAllValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequiredWithoutAll)(nil)

func (t *RequiredWithoutAll) Validate() error {
	return ValidateRequiredWithoutAll(t)
}
