// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilEq is returned when the Eq is nil.
	ErrNilEq = errors.New("input Eq is nil")

	// ErrEqStatusEqValidation is the error returned when the field does not equal \"active\".
	ErrEqStatusEqValidation = govaliderrors.ValidationError{Reason: "field Status must equal \"active\"", Path: "Eq.Status", Type: "eq"}

	// ErrEqCountEqValidation is the error returned when the field does not equal 100.
	ErrEqCountEqValidation = govaliderrors.ValidationError{Reason: "field Count must equal 100", Path: "Eq.Count", Type: "eq"}
)

func ValidateEq(t *Eq) error {
	if t == nil {
		return ErrNilEq
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Status == "active") {
		err := ErrEqStatusEqValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if !(t.Count == 100) {
		err := ErrEqCountEqValidation
		err.Value = t.Count
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Eq)(nil)

func (t *Eq) Validate() error {
	return ValidateEq(t)
}
