// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilUnique is returned when the Unique is nil.
	ErrNilUnique = errors.New("input Unique is nil")

	// ErrUniqueTagsUniqueValidation is the error returned when the field contains duplicate values.
	ErrUniqueTagsUniqueValidation = govaliderrors.ValidationError{Reason: "tags must contain unique values", Path: "tags", Type: "unique"}

	// ErrUniqueIDsUniqueValidation is the error returned when the field contains duplicate values.
	ErrUniqueIDsUniqueValidation = govaliderrors.ValidationError{Reason: "ids must contain unique values", Path: "ids", Type: "unique"}
)

func ValidateUnique(t *Unique) error {
	if t == nil {
		return ErrNilUnique
	}

	var errs govaliderrors.ValidationErrors

	if func() bool {
		seen := make(map[interface{}]struct{})
		for _, v := range t.Tags {
			if _, exists := seen[v]; exists {
				return true
			}
			seen[v] = struct{}{}
		}
		return false
	}() {
		err := ErrUniqueTagsUniqueValidation
		err.Value = t.Tags
		errs = append(errs, err)
	}

	if func() bool {
		seen := make(map[interface{}]struct{})
		for _, v := range t.IDs {
			if _, exists := seen[v]; exists {
				return true
			}
			seen[v] = struct{}{}
		}
		return false
	}() {
		err := ErrUniqueIDsUniqueValidation
		err.Value = t.IDs
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Unique)(nil)

func (t *Unique) Validate() error {
	return ValidateUnique(t)
}
