// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilRequiredWithAll is returned when the RequiredWithAll is nil.
	ErrNilRequiredWithAll = errors.New("input RequiredWithAll is nil")

	// ErrRequiredWithAllFullNameRequiredWithAllValidation is the error returned when the field is required because all other fields are present.
	ErrRequiredWithAllFullNameRequiredWithAllValidation = govaliderrors.ValidationError{Reason: "full_name is required when all of FirstName, LastName are present", Path: "full_name", Type: "required_with_all"}
)

func ValidateRequiredWithAll(t *RequiredWithAll) error {
	if t == nil {
		return ErrNilRequiredWithAll
	}

	var errs govaliderrors.ValidationErrors

	if (t.FirstName != "" && t.LastName != "") && t.FullName == "" {
		err := ErrRequiredWithAllFullNameRequiredWithAllValidation
		err.Value = t.FullName
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequiredWithAll)(nil)

func (t *RequiredWithAll) Validate() error {
	return ValidateRequiredWithAll(t)
}
