// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilExcludedWithoutAll is returned when the ExcludedWithoutAll is nil.
	ErrNilExcludedWithoutAll = errors.New("input ExcludedWithoutAll is nil")

	// ErrExcludedWithoutAllConflictingFeatureExcludedWithoutAllValidation is the error returned when the field must be absent because all other fields are absent.
	ErrExcludedWithoutAllConflictingFeatureExcludedWithoutAllValidation = govaliderrors.ValidationError{Reason: "field ConflictingFeature must be absent when all of FeatureA, FeatureB are absent", Path: "ExcludedWithoutAll.ConflictingFeature", Type: "excluded_without_all"}
)

func ValidateExcludedWithoutAll(t *ExcludedWithoutAll) error {
	if t == nil {
		return ErrNilExcludedWithoutAll
	}

	var errs govaliderrors.ValidationErrors

	if (t.FeatureA == "" && t.FeatureB == "") && t.ConflictingFeature != "" {
		err := ErrExcludedWithoutAllConflictingFeatureExcludedWithoutAllValidation
		err.Value = t.ConflictingFeature
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludedWithoutAll)(nil)

func (t *ExcludedWithoutAll) Validate() error {
	return ValidateExcludedWithoutAll(t)
}
