// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilAlphanum is returned when the Alphanum is nil.
	ErrNilAlphanum = errors.New("input Alphanum is nil")

	// ErrAlphanumCodeAlphanumValidation is the error returned when the field contains non-alphanumeric characters.
	ErrAlphanumCodeAlphanumValidation = govaliderrors.ValidationError{Reason: "field Code must contain only alphanumeric characters", Path: "Alphanum.Code", Type: "alphanum"}
)

func ValidateAlphanum(t *Alphanum) error {
	if t == nil {
		return ErrNilAlphanum
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsAlphanum(t.Code) {
		err := ErrAlphanumCodeAlphanumValidation
		err.Value = t.Code
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Alphanum)(nil)

func (t *Alphanum) Validate() error {
	return ValidateAlphanum(t)
}
