// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems = errors.New("input MinItems is nil")

	// ErrMinItemsItemsMinItemsValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrMinItemsItemsMinItemsValidation = govaliderrors.ValidationError{Reason: "items must have a minimum of 2 items", Path: "items", Type: "minitems"}

	// ErrMinItemsMetadataMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsMetadataMinItemsValidation = govaliderrors.ValidationError{Reason: "metadata must have a minimum of 1 items", Path: "metadata", Type: "minitems"}

	// ErrMinItemsChanFieldMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsChanFieldMinItemsValidation = govaliderrors.ValidationError{Reason: "chan_field must have a minimum of 1 items", Path: "chan_field", Type: "minitems"}
)

func ValidateMinItems(t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Items) < 2 {
		err := ErrMinItemsItemsMinItemsValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if len(t.Metadata) < 1 {
		err := ErrMinItemsMetadataMinItemsValidation
		err.Value = t.Metadata
		errs = append(errs, err)
	}

	if len(t.ChanField) < 1 {
		err := ErrMinItemsChanFieldMinItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MinItems)(nil)

func (t *MinItems) Validate() error {
	return ValidateMinItems(t)
}
