// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilOneOf is returned when the OneOf is nil.
	ErrNilOneOf = errors.New("input OneOf is nil")

	// ErrOneOfColorOneofValidation is the error returned when the field is not one of the allowed values.
	ErrOneOfColorOneofValidation = govaliderrors.ValidationError{Reason: "field Color must be one of red green blue", Path: "OneOf.Color", Type: "oneof"}

	// ErrOneOfLevelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrOneOfLevelOneofValidation = govaliderrors.ValidationError{Reason: "field Level must be one of 1 2 3", Path: "OneOf.Level", Type: "oneof"}
)

func ValidateOneOf(t *OneOf) error {
	if t == nil {
		return ErrNilOneOf
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Color == "red" || t.Color == "green" || t.Color == "blue") {
		err := ErrOneOfColorOneofValidation
		err.Value = t.Color
		errs = append(errs, err)
	}

	if !(t.Level == 1 || t.Level == 2 || t.Level == 3) {
		err := ErrOneOfLevelOneofValidation
		err.Value = t.Level
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*OneOf)(nil)

func (t *OneOf) Validate() error {
	return ValidateOneOf(t)
}
