// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilExcludedWithout is returned when the ExcludedWithout is nil.
	ErrNilExcludedWithout = errors.New("input ExcludedWithout is nil")

	// ErrExcludedWithoutFreeFeatureExcludedWithoutValidation is the error returned when the field must be absent because other fields are absent.
	ErrExcludedWithoutFreeFeatureExcludedWithoutValidation = govaliderrors.ValidationError{Reason: "free_feature must be absent when any of Premium are absent", Path: "free_feature", Type: "excluded_without"}
)

func ValidateExcludedWithout(t *ExcludedWithout) error {
	if t == nil {
		return ErrNilExcludedWithout
	}

	var errs govaliderrors.ValidationErrors

	if (t.Premium == "") && t.FreeFeature != "" {
		err := ErrExcludedWithoutFreeFeatureExcludedWithoutValidation
		err.Value = t.FreeFeature
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludedWithout)(nil)

func (t *ExcludedWithout) Validate() error {
	return ValidateExcludedWithout(t)
}
