// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"strings"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilExcludesAll is returned when the ExcludesAll is nil.
	ErrNilExcludesAll = errors.New("input ExcludesAll is nil")

	// ErrExcludesAllCommentExcludesallValidation is the error returned when the field contains any of the excluded characters.
	ErrExcludesAllCommentExcludesallValidation = govaliderrors.ValidationError{Reason: "field Comment must not contain any of these characters: <>", Path: "ExcludesAll.Comment", Type: "excludesall"}
)

func ValidateExcludesAll(t *ExcludesAll) error {
	if t == nil {
		return ErrNilExcludesAll
	}

	var errs govaliderrors.ValidationErrors

	if strings.ContainsAny(t.Comment, "<>") {
		err := ErrExcludesAllCommentExcludesallValidation
		err.Value = t.Comment
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludesAll)(nil)

func (t *ExcludesAll) Validate() error {
	return ValidateExcludesAll(t)
}
