// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilExcludedWith is returned when the ExcludedWith is nil.
	ErrNilExcludedWith = errors.New("input ExcludedWith is nil")

	// ErrExcludedWithAdminPanelExcludedWithValidation is the error returned when the field must be absent because other fields are present.
	ErrExcludedWithAdminPanelExcludedWithValidation = govaliderrors.ValidationError{Reason: "admin_panel must be absent when any of GuestMode are present", Path: "admin_panel", Type: "excluded_with"}
)

func ValidateExcludedWith(t *ExcludedWith) error {
	if t == nil {
		return ErrNilExcludedWith
	}

	var errs govaliderrors.ValidationErrors

	if (t.GuestMode != "") && t.AdminPanel != "" {
		err := ErrExcludedWithAdminPanelExcludedWithValidation
		err.Value = t.AdminPanel
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludedWith)(nil)

func (t *ExcludedWith) Validate() error {
	return ValidateExcludedWith(t)
}
