// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilRequiredUnless is returned when the RequiredUnless is nil.
	ErrNilRequiredUnless = errors.New("input RequiredUnless is nil")

	// ErrRequiredUnlessActiveFieldRequiredUnlessValidation is the error returned when the field is required unless another field has a specific value.
	ErrRequiredUnlessActiveFieldRequiredUnlessValidation = govaliderrors.ValidationError{Reason: "field ActiveField is required unless Status equals \"inactive\"", Path: "RequiredUnless.ActiveField", Type: "required_unless"}
)

func ValidateRequiredUnless(t *RequiredUnless) error {
	if t == nil {
		return ErrNilRequiredUnless
	}

	var errs govaliderrors.ValidationErrors

	if t.Status != "inactive" && t.ActiveField == "" {
		err := ErrRequiredUnlessActiveFieldRequiredUnlessValidation
		err.Value = t.ActiveField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*RequiredUnless)(nil)

func (t *RequiredUnless) Validate() error {
	return ValidateRequiredUnless(t)
}
