// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilExcludedUnless is returned when the ExcludedUnless is nil.
	ErrNilExcludedUnless = errors.New("input ExcludedUnless is nil")

	// ErrExcludedUnlessInactiveFieldExcludedUnlessValidation is the error returned when the field must be absent unless another field has a specific value.
	ErrExcludedUnlessInactiveFieldExcludedUnlessValidation = govaliderrors.ValidationError{Reason: "inactive_field must be absent unless Status equals \"active\"", Path: "inactive_field", Type: "excluded_unless"}
)

func ValidateExcludedUnless(t *ExcludedUnless) error {
	if t == nil {
		return ErrNilExcludedUnless
	}

	var errs govaliderrors.ValidationErrors

	if t.Status != "active" && t.InactiveField != "" {
		err := ErrExcludedUnlessInactiveFieldExcludedUnlessValidation
		err.Value = t.InactiveField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludedUnless)(nil)

func (t *ExcludedUnless) Validate() error {
	return ValidateExcludedUnless(t)
}
