// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilLTE is returned when the LTE is nil.
	ErrNilLTE = errors.New("input LTE is nil")

	// ErrLTEAgeLTEValidation is the error returned when the value of the field is greater than 100.
	ErrLTEAgeLTEValidation = govaliderrors.ValidationError{Reason: "age must be less than or equal to 100", Path: "age", Type: "lte"}
)

func ValidateLTE(t *LTE) error {
	if t == nil {
		return ErrNilLTE
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age <= 100) {
		err := ErrLTEAgeLTEValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*LTE)(nil)

func (t *LTE) Validate() error {
	return ValidateLTE(t)
}
