// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilIsDefault is returned when the IsDefault is nil.
	ErrNilIsDefault = errors.New("input IsDefault is nil")

	// ErrIsDefaultOptionalFieldIsdefaultValidation is the error returned when the field is not at its default/zero value.
	ErrIsDefaultOptionalFieldIsdefaultValidation = govaliderrors.ValidationError{Reason: "optional_field must be at its default value", Path: "optional_field", Type: "isdefault"}

	// ErrIsDefaultOptionalNumberIsdefaultValidation is the error returned when the field is not at its default/zero value.
	ErrIsDefaultOptionalNumberIsdefaultValidation = govaliderrors.ValidationError{Reason: "optional_number must be at its default value", Path: "optional_number", Type: "isdefault"}
)

func ValidateIsDefault(t *IsDefault) error {
	if t == nil {
		return ErrNilIsDefault
	}

	var errs govaliderrors.ValidationErrors

	if t.OptionalField != "" {
		err := ErrIsDefaultOptionalFieldIsdefaultValidation
		err.Value = t.OptionalField
		errs = append(errs, err)
	}

	if t.OptionalNumber != 0 {
		err := ErrIsDefaultOptionalNumberIsdefaultValidation
		err.Value = t.OptionalNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*IsDefault)(nil)

func (t *IsDefault) Validate() error {
	return ValidateIsDefault(t)
}
