// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilFQDN is returned when the FQDN is nil.
	ErrNilFQDN = errors.New("input FQDN is nil")

	// ErrFQDNDomainFQDNValidation is the error returned when the field is not a fully qualified domain name.
	ErrFQDNDomainFQDNValidation = govaliderrors.ValidationError{Reason: "field Domain must be a fully qualified domain name", Path: "FQDN.Domain", Type: "fqdn"}
)

func ValidateFQDN(t *FQDN) error {
	if t == nil {
		return ErrNilFQDN
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidFQDN(t.Domain) {
		err := ErrFQDNDomainFQDNValidation
		err.Value = t.Domain
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FQDN)(nil)

func (t *FQDN) Validate() error {
	return ValidateFQDN(t)
}
