// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"strings"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilContainsAny is returned when the ContainsAny is nil.
	ErrNilContainsAny = errors.New("input ContainsAny is nil")

	// ErrContainsAnyPasswordContainsanyValidation is the error returned when the field does not contain any of the specified characters.
	ErrContainsAnyPasswordContainsanyValidation = govaliderrors.ValidationError{Reason: "field Password must contain at least one of these characters: !@#$", Path: "ContainsAny.Password", Type: "containsany"}
)

func ValidateContainsAny(t *ContainsAny) error {
	if t == nil {
		return ErrNilContainsAny
	}

	var errs govaliderrors.ValidationErrors

	if !strings.ContainsAny(t.Password, "!@#$") {
		err := ErrContainsAnyPasswordContainsanyValidation
		err.Value = t.Password
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ContainsAny)(nil)

func (t *ContainsAny) Validate() error {
	return ValidateContainsAny(t)
}
