// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilExcludedWithAll is returned when the ExcludedWithAll is nil.
	ErrNilExcludedWithAll = errors.New("input ExcludedWithAll is nil")

	// ErrExcludedWithAllEditButtonExcludedWithAllValidation is the error returned when the field must be absent because all other fields are present.
	ErrExcludedWithAllEditButtonExcludedWithAllValidation = govaliderrors.ValidationError{Reason: "field EditButton must be absent when all of ReadOnly, Archived are present", Path: "ExcludedWithAll.EditButton", Type: "excluded_with_all"}
)

func ValidateExcludedWithAll(t *ExcludedWithAll) error {
	if t == nil {
		return ErrNilExcludedWithAll
	}

	var errs govaliderrors.ValidationErrors

	if (t.ReadOnly != "" && t.Archived != "") && t.EditButton != "" {
		err := ErrExcludedWithAllEditButtonExcludedWithAllValidation
		err.Value = t.EditButton
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ExcludedWithAll)(nil)

func (t *ExcludedWithAll) Validate() error {
	return ValidateExcludedWithAll(t)
}
