// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMinLength is returned when the MinLength is nil.
	ErrNilMinLength = errors.New("input MinLength is nil")

	// ErrMinLengthNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrMinLengthNameMinLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a minimum length of 3", Path: "MinLength.Name", Type: "minlength"}
)

func ValidateMinLength(t *MinLength) error {
	if t == nil {
		return ErrNilMinLength
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Name) < 3 {
		err := ErrMinLengthNameMinLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MinLength)(nil)

func (t *MinLength) Validate() error {
	return ValidateMinLength(t)
}
