// Code generated by govalid; DO NOT EDIT.
package lte

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilLTE is returned when the LTE is nil.
	ErrNilLTE = errors.New("input LTE is nil")

	// ErrLTEAgeLTEValidation is the error returned when the value of the field is greater than 100.
	ErrLTEAgeLTEValidation = govaliderrors.ValidationError{Reason: "field Age must be less than or equal to 100", Path: "LTE.Age", Type: "lte"}

	// ErrLTEScoreLTEValidation is the error returned when the value of the field is greater than 10.5.
	ErrLTEScoreLTEValidation = govaliderrors.ValidationError{Reason: "field Score must be less than or equal to 10.5", Path: "LTE.Score", Type: "lte"}

	// Deprecated: Use ErrLTEStructValueLTEValidation
	//
	// ErrLTEValueLTEValidation is deprecated and is kept for compatibility purpose.
	ErrLTEValueLTEValidation = ErrLTEStructValueLTEValidation

	// ErrLTEStructValueLTEValidation is the error returned when the value of the field is greater than 50.
	ErrLTEStructValueLTEValidation = govaliderrors.ValidationError{Reason: "field Value must be less than or equal to 50", Path: "LTE.Struct.Value", Type: "lte"}
)

func ValidateLTE(t *LTE) error {
	if t == nil {
		return ErrNilLTE
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age <= 100) {
		err := ErrLTEAgeLTEValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if !(t.Score <= 10.5) {
		err := ErrLTEScoreLTEValidation
		err.Value = t.Score
		errs = append(errs, err)
	}

	{
		t := t.Struct

		if !(t.Value <= 50) {
			err := ErrLTEStructValueLTEValidation
			err.Value = t.Value
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*LTE)(nil)

func (t *LTE) Validate() error {
	return ValidateLTE(t)
}
