// Code generated by govalid; DO NOT EDIT.
package lt

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilLT is returned when the LT is nil.
	ErrNilLT = errors.New("input LT is nil")

	// ErrLTIntLTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTIntLTValidation = govaliderrors.ValidationError{Reason: "field Int must be less than 1", Path: "LT.Int", Type: "lt"}

	// ErrLTInt8LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTInt8LTValidation = govaliderrors.ValidationError{Reason: "field Int8 must be less than 1", Path: "LT.Int8", Type: "lt"}

	// ErrLTInt16LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTInt16LTValidation = govaliderrors.ValidationError{Reason: "field Int16 must be less than 1", Path: "LT.Int16", Type: "lt"}

	// ErrLTInt32LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTInt32LTValidation = govaliderrors.ValidationError{Reason: "field Int32 must be less than 1", Path: "LT.Int32", Type: "lt"}

	// ErrLTInt64LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTInt64LTValidation = govaliderrors.ValidationError{Reason: "field Int64 must be less than 1", Path: "LT.Int64", Type: "lt"}

	// ErrLTFloat32LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTFloat32LTValidation = govaliderrors.ValidationError{Reason: "field Float32 must be less than 1", Path: "LT.Float32", Type: "lt"}

	// ErrLTFloat64LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTFloat64LTValidation = govaliderrors.ValidationError{Reason: "field Float64 must be less than 1", Path: "LT.Float64", Type: "lt"}

	// ErrLTUintLTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTUintLTValidation = govaliderrors.ValidationError{Reason: "field Uint must be less than 1", Path: "LT.Uint", Type: "lt"}

	// ErrLTUint8LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTUint8LTValidation = govaliderrors.ValidationError{Reason: "field Uint8 must be less than 1", Path: "LT.Uint8", Type: "lt"}

	// ErrLTUint16LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTUint16LTValidation = govaliderrors.ValidationError{Reason: "field Uint16 must be less than 1", Path: "LT.Uint16", Type: "lt"}

	// ErrLTUint32LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTUint32LTValidation = govaliderrors.ValidationError{Reason: "field Uint32 must be less than 1", Path: "LT.Uint32", Type: "lt"}

	// ErrLTUint64LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTUint64LTValidation = govaliderrors.ValidationError{Reason: "field Uint64 must be less than 1", Path: "LT.Uint64", Type: "lt"}

	// ErrLTUintptrLTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTUintptrLTValidation = govaliderrors.ValidationError{Reason: "field Uintptr must be less than 1", Path: "LT.Uintptr", Type: "lt"}

	// ErrLTComplex64LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTComplex64LTValidation = govaliderrors.ValidationError{Reason: "field Complex64 must be less than 1", Path: "LT.Complex64", Type: "lt"}

	// ErrLTComplex128LTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTComplex128LTValidation = govaliderrors.ValidationError{Reason: "field Complex128 must be less than 1", Path: "LT.Complex128", Type: "lt"}

	// Deprecated: Use ErrLTStructIntLTValidation
	//
	// ErrLTIntLTValidation is deprecated and is kept for compatibility purpose.
	ErrLTIntLTValidation = ErrLTStructIntLTValidation

	// ErrLTStructIntLTValidation is the error returned when the value of the field is greater than the 1.
	ErrLTStructIntLTValidation = govaliderrors.ValidationError{Reason: "field Int must be less than 1", Path: "LT.Struct.Int", Type: "lt"}
)

func ValidateLT(t *LT) error {
	if t == nil {
		return ErrNilLT
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Int < 1) {
		err := ErrLTIntLTValidation
		err.Value = t.Int
		errs = append(errs, err)
	}

	if !(t.Int8 < 1) {
		err := ErrLTInt8LTValidation
		err.Value = t.Int8
		errs = append(errs, err)
	}

	if !(t.Int16 < 1) {
		err := ErrLTInt16LTValidation
		err.Value = t.Int16
		errs = append(errs, err)
	}

	if !(t.Int32 < 1) {
		err := ErrLTInt32LTValidation
		err.Value = t.Int32
		errs = append(errs, err)
	}

	if !(t.Int64 < 1) {
		err := ErrLTInt64LTValidation
		err.Value = t.Int64
		errs = append(errs, err)
	}

	if !(t.Float32 < 1) {
		err := ErrLTFloat32LTValidation
		err.Value = t.Float32
		errs = append(errs, err)
	}

	if !(t.Float64 < 1) {
		err := ErrLTFloat64LTValidation
		err.Value = t.Float64
		errs = append(errs, err)
	}

	if !(t.Uint < 1) {
		err := ErrLTUintLTValidation
		err.Value = t.Uint
		errs = append(errs, err)
	}

	if !(t.Uint8 < 1) {
		err := ErrLTUint8LTValidation
		err.Value = t.Uint8
		errs = append(errs, err)
	}

	if !(t.Uint16 < 1) {
		err := ErrLTUint16LTValidation
		err.Value = t.Uint16
		errs = append(errs, err)
	}

	if !(t.Uint32 < 1) {
		err := ErrLTUint32LTValidation
		err.Value = t.Uint32
		errs = append(errs, err)
	}

	if !(t.Uint64 < 1) {
		err := ErrLTUint64LTValidation
		err.Value = t.Uint64
		errs = append(errs, err)
	}

	if !(t.Uintptr < 1) {
		err := ErrLTUintptrLTValidation
		err.Value = t.Uintptr
		errs = append(errs, err)
	}

	if !(t.Complex64 < 1) {
		err := ErrLTComplex64LTValidation
		err.Value = t.Complex64
		errs = append(errs, err)
	}

	if !(t.Complex128 < 1) {
		err := ErrLTComplex128LTValidation
		err.Value = t.Complex128
		errs = append(errs, err)
	}

	{
		t := t.Struct

		if !(t.Int < 1) {
			err := ErrLTStructIntLTValidation
			err.Value = t.Int
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*LT)(nil)

func (t *LT) Validate() error {
	return ValidateLT(t)
}
