// Code generated by govalid; DO NOT EDIT.
package partial

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilPartial is returned when the Partial is nil.
	ErrNilPartial = errors.New("input Partial is nil")

	// ErrPartialNameRequiredValidation is returned when the Name is required but not provided.
	ErrPartialNameRequiredValidation = govaliderrors.ValidationError{Reason: "field Name is required", Path: "Partial.Name", Type: "required"}
)

func ValidatePartial(t *Partial) error {
	if t == nil {
		return ErrNilPartial
	}

	var errs govaliderrors.ValidationErrors

	if t.Name == "" {
		err := ErrPartialNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Partial)(nil)

func (t *Partial) Validate() error {
	return ValidatePartial(t)
}
