// Code generated by generate-validators; DO NOT EDIT.
package rules

import (
	"fmt"
	"go/ast"
	"strings"

	"github.com/gostaticanalysis/codegen"

	"github.com/sivchari/govalid/internal/validator"
	"github.com/sivchari/govalid/internal/validator/registry"
)

type ipv6Validator struct {
	pass       *codegen.Pass
	field      *ast.Field
	structName string
	ruleName   string
	parentPath string
}

var _ validator.Validator = (*ipv6Validator)(nil)

const ipv6Key = "%s-ipv6"

func (v *ipv6Validator) Validate() string {
	return fmt.Sprintf("ip := net.ParseIP(t.%s); ip == nil || ip.To4() != nil", v.FieldName())
}

func (v *ipv6Validator) FieldName() string {
	return v.field.Names[0].Name
}

func (v *ipv6Validator) FieldPath() validator.FieldPath {
	return validator.NewFieldPath(v.structName, v.parentPath, v.FieldName())
}

func (v *ipv6Validator) Err() string {
	key := fmt.Sprintf(ipv6Key, v.FieldPath().CleanedPath())

	if validator.GeneratorMemory[key] {
		return ""
	}

	validator.GeneratorMemory[key] = true

	const deprecationNoticeTemplate = `
		// Deprecated: Use [@ERRVARIABLE]
		//
		// [@LEGACYERRVAR] is deprecated and is kept for compatibility purpose.
		[@LEGACYERRVAR] = [@ERRVARIABLE]
  `

	const errTemplate = `
	  // [@ERRVARIABLE] is returned when the [@FIELD] fails ipv6 validation.
	  [@ERRVARIABLE] = govaliderrors.ValidationError{Reason:"field [@FIELD] failed ipv6 validation",Path:"[@PATH]",Type:"[@TYPE]"}
	`

	legacyErrVarName := fmt.Sprintf("Err%s%sIpv6Validation", v.structName, v.FieldName())
	currentErrVarName := v.ErrVariable()

	replacer := strings.NewReplacer(
		"[@ERRVARIABLE]", currentErrVarName,
		"[@LEGACYERRVAR]", legacyErrVarName,
		"[@FIELD]", v.FieldName(),
		"[@PATH]", v.FieldPath().String(),
		"[@TYPE]", v.ruleName,
	)

	if currentErrVarName != legacyErrVarName {
		return replacer.Replace(deprecationNoticeTemplate + errTemplate)
	}

	return replacer.Replace(errTemplate)
}

func (v *ipv6Validator) ErrVariable() string {
	return strings.ReplaceAll("Err[@PATH]Ipv6Validation", "[@PATH]", v.FieldPath().CleanedPath())
}

func (v *ipv6Validator) Imports() []string {
	return []string{"net"}
}

// ValidateIpv6 creates a new ipv6 validator for the given field.
func ValidateIpv6(input registry.ValidatorInput) validator.Validator {
	return &ipv6Validator{
		pass:       input.Pass,
		field:      input.Field,
		structName: input.StructName,
		ruleName:   input.RuleName,
		parentPath: input.ParentPath,
	}
}
