// Code generated by generate-validators; DO NOT EDIT.
package rules

import (
	"fmt"
	"go/ast"
	"strings"

	"github.com/gostaticanalysis/codegen"

	"github.com/sivchari/govalid/internal/validator"
	"github.com/sivchari/govalid/internal/validator/registry"
)

type required_unlessValidator struct {
	pass       *codegen.Pass
	field      *ast.Field
	structName string
	ruleName   string
	parentPath string
}

var _ validator.Validator = (*required_unlessValidator)(nil)

const required_unlessKey = "%s-required_unless"

func (v *required_unlessValidator) Validate() string {
	// TODO: Implement validation logic
	// Return a Go expression that evaluates to true when validation fails
    return ""
}

func (v *required_unlessValidator) FieldName() string {
	return v.field.Names[0].Name
}

func (v *required_unlessValidator) FieldPath() validator.FieldPath {
	return validator.NewFieldPath(v.structName, v.parentPath, v.FieldName())
}

func (v *required_unlessValidator) Err() string {
	key := fmt.Sprintf(required_unlessKey, v.FieldPath().CleanedPath())

	if validator.GeneratorMemory[key] {
		return ""
	}

	validator.GeneratorMemory[key] = true

  const deprecationNoticeTemplate = `
		// Deprecated: Use [@ERRVARIABLE]
		//
		// [@LEGACYERRVAR] is deprecated and is kept for compatibility purpose.
		[@LEGACYERRVAR] = [@ERRVARIABLE]
  `

	const errTemplate = `
	  // [@ERRVARIABLE] is returned when the [@FIELD] fails required_unless validation.
	  [@ERRVARIABLE] = govaliderrors.ValidationError{Reason:"field [@FIELD] failed required_unless validation",Path:"[@PATH]",Type:"[@TYPE]"}
	`

  legacyErrVarName := fmt.Sprintf("Err%s%sRequired_unlessValidation", v.structName, v.FieldName())
	currentErrVarName := v.ErrVariable()

	replacer := strings.NewReplacer(
        "[@ERRVARIABLE]", currentErrVarName,
		"[@LEGACYERRVAR]", legacyErrVarName,
		"[@FIELD]", v.FieldName(),
		"[@PATH]", v.FieldPath().String(),
		"[@TYPE]", v.ruleName,
	)

  if currentErrVarName != legacyErrVarName {
		return replacer.Replace(deprecationNoticeTemplate + errTemplate)
	}

	return replacer.Replace(errTemplate)
}

func (v *required_unlessValidator) ErrVariable() string {
	return strings.ReplaceAll("Err[@PATH]Required_unlessValidation", "[@PATH]", v.FieldPath().CleanedPath())
}

func (v *required_unlessValidator) Imports() []string {
	// TODO: Add any required imports
	return []string{}
}

// ValidateRequired_unless creates a new required_unless validator for the given field.
func ValidateRequired_unless(input registry.ValidatorInput) validator.Validator {
	return &required_unlessValidator{
		pass:       input.Pass,
		field:      input.Field,
		structName: input.StructName,
		ruleName:   input.RuleName,
		parentPath: input.ParentPath,
	}
}
