//go:build test

// Code generated by govalid; DO NOT EDIT.
package testfixture

import (
	"errors"
	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilPersonRequest is returned when the PersonRequest is nil.
	ErrNilPersonRequest = errors.New("input PersonRequest is nil")

	// ErrPersonRequestEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrPersonRequestEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "PersonRequest.Email", Type: "email"}
)

func ValidatePersonRequest(t *PersonRequest) error {
	if t == nil {
		return ErrNilPersonRequest
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrPersonRequestEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*PersonRequest)(nil)

func (t *PersonRequest) Validate() error {
	return ValidatePersonRequest(t)
}
