// Code generated by generate-validators; DO NOT EDIT.
package govalid

import (
	"log"

	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/registry/initializers"
)

func init() {
	// Initialize the validator registry with all built-in validators
	if err := registry.Init(
		registry.AddValidators(initializers.All()...),
	); err != nil {
		log.Fatalf("Failed to initialize validator registry: %v", err)
	}
}
