// Code generated by govalid; DO NOT EDIT.
package maxitems

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMaxItems is returned when the MaxItems is nil.
	ErrNilMaxItems = errors.New("input MaxItems is nil")

	// ErrMaxItemsSliceMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 5.
	ErrMaxItemsSliceMaxItemsValidation = govaliderrors.ValidationError{Reason: "field Slice must have a maximum of 5 items", Path: "MaxItems.Slice", Type: "maxitems"}

	// ErrMaxItemsArrayMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 3.
	ErrMaxItemsArrayMaxItemsValidation = govaliderrors.ValidationError{Reason: "field Array must have a maximum of 3 items", Path: "MaxItems.Array", Type: "maxitems"}

	// ErrMaxItemsMapFieldMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 4.
	ErrMaxItemsMapFieldMaxItemsValidation = govaliderrors.ValidationError{Reason: "field MapField must have a maximum of 4 items", Path: "MaxItems.MapField", Type: "maxitems"}

	// ErrMaxItemsChanFieldMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 2.
	ErrMaxItemsChanFieldMaxItemsValidation = govaliderrors.ValidationError{Reason: "field ChanField must have a maximum of 2 items", Path: "MaxItems.ChanField", Type: "maxitems"}

	// Deprecated: Use ErrMaxItemsStructItemsMaxItemsValidation
	//
	// ErrMaxItemsItemsMaxItemsValidation is deprecated and is kept for compatibility purpose.
	ErrMaxItemsItemsMaxItemsValidation = ErrMaxItemsStructItemsMaxItemsValidation

	// ErrMaxItemsStructItemsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 2.
	ErrMaxItemsStructItemsMaxItemsValidation = govaliderrors.ValidationError{Reason: "field Items must have a maximum of 2 items", Path: "MaxItems.Struct.Items", Type: "maxitems"}
)

func ValidateMaxItems(t *MaxItems) error {
	if t == nil {
		return ErrNilMaxItems
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Slice) > 5 {
		err := ErrMaxItemsSliceMaxItemsValidation
		err.Value = t.Slice
		errs = append(errs, err)
	}

	if len(t.Array) > 3 {
		err := ErrMaxItemsArrayMaxItemsValidation
		err.Value = t.Array
		errs = append(errs, err)
	}

	if len(t.MapField) > 4 {
		err := ErrMaxItemsMapFieldMaxItemsValidation
		err.Value = t.MapField
		errs = append(errs, err)
	}

	if len(t.ChanField) > 2 {
		err := ErrMaxItemsChanFieldMaxItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	{
		t := t.Struct

		if len(t.Items) > 2 {
			err := ErrMaxItemsStructItemsMaxItemsValidation
			err.Value = t.Items
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*MaxItems)(nil)

func (t *MaxItems) Validate() error {
	return ValidateMaxItems(t)
}
