// Code generated by govalid; DO NOT EDIT.
package length

import (
	"errors"
	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilLength is returned when the Length is nil.
	ErrNilLength = errors.New("input Length is nil")

	// ErrLengthStringLengthValidation is the error returned when the length of the field is not exactly 7.
	ErrLengthStringLengthValidation = govaliderrors.ValidationError{Reason: "field String length must be exactly 7", Path: "Length.String", Type: "length"}

	// Deprecated: Use ErrLengthStructNameLengthValidation
	//
	// ErrLengthNameLengthValidation is deprecated and is kept for compatibility purpose.
	ErrLengthNameLengthValidation = ErrLengthStructNameLengthValidation

	// ErrLengthStructNameLengthValidation is the error returned when the length of the field is not exactly 10.
	ErrLengthStructNameLengthValidation = govaliderrors.ValidationError{Reason: "field Name length must be exactly 10", Path: "Length.Struct.Name", Type: "length"}
)

func ValidateLength(t *Length) error {
	if t == nil {
		return ErrNilLength
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.String) != 7 {
		err := ErrLengthStringLengthValidation
		err.Value = t.String
		errs = append(errs, err)
	}

	{
		t := t.Struct

		if utf8.RuneCountInString(t.Name) != 10 {
			err := ErrLengthStructNameLengthValidation
			err.Value = t.Name
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Length)(nil)

func (t *Length) Validate() error {
	return ValidateLength(t)
}
