// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/validator/registry"
)

// All returns all built-in validator initializers.
func All() []registry.ValidatorInitializer {
	return []registry.ValidatorInitializer{
		AlphaInitializer{},
		AlphanumInitializer{},
		BooleanInitializer{},
		CelInitializer{},
		ContainsanyInitializer{},
		DateInitializer{},
		EmailInitializer{},
		EnumInitializer{},
		EqInitializer{},
		Excluded_ifInitializer{},
		Excluded_unlessInitializer{},
		Excluded_withInitializer{},
		Excluded_with_allInitializer{},
		Excluded_withoutInitializer{},
		Excluded_without_allInitializer{},
		ExcludesInitializer{},
		ExcludesallInitializer{},
		FqdnInitializer{},
		GtInitializer{},
		GteInitializer{},
		Ipv4Initializer{},
		Ipv6Initializer{},
		IscolourInitializer{},
		IsdefaultInitializer{},
		LatitudeInitializer{},
		LengthInitializer{},
		LongitudeInitializer{},
		LowercaseInitializer{},
		LtInitializer{},
		LteInitializer{},
		MaxdurationInitializer{},
		MaxitemsInitializer{},
		MaxlengthInitializer{},
		MinInitializer{},
		MindurationInitializer{},
		MinitemsInitializer{},
		MinlengthInitializer{},
		NeInitializer{},
		NumberInitializer{},
		NumericInitializer{},
		OneofInitializer{},
		RequiredInitializer{},
		Required_ifInitializer{},
		Required_unlessInitializer{},
		Required_withInitializer{},
		Required_with_allInitializer{},
		Required_withoutInitializer{},
		Required_without_allInitializer{},
		UniqueInitializer{},
		UriInitializer{},
		UrlInitializer{},
		UuidInitializer{},
	}
}
