// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/validator/registry"
)

// All returns all built-in validator initializers.
func All() []registry.ValidatorInitializer {
	return []registry.ValidatorInitializer{
		AlphaInitializer{},
		CelInitializer{},
		EmailInitializer{},
		EnumInitializer{},
		GtInitializer{},
		GteInitializer{},
		Ipv4Initializer{},
		Ipv6Initializer{},
		DateInitializer{},
		LengthInitializer{},
		LtInitializer{},
		LteInitializer{},
		MaxitemsInitializer{},
		MaxlengthInitializer{},
		MinitemsInitializer{},
		MinlengthInitializer{},
		NumericInitializer{},
		RequiredInitializer{},
		UrlInitializer{},
		UuidInitializer{},
	}
}
