// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// AlphanumInitializer implements ValidatorInitializer for the alphanum validator.
type AlphanumInitializer struct{}

// Marker returns the marker identifier for the alphanum validator.
func (a AlphanumInitializer) Marker() string {
	return markers.GoValidMarkerAlphanum
}

// Init initializes the alphanum validator factory.
func (a AlphanumInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateAlphanum
}
