// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// AlphaInitializer implements ValidatorInitializer for the alpha validator.
type AlphaInitializer struct{}

// Marker returns the marker identifier for the alpha validator.
func (a AlphaInitializer) Marker() string {
	return markers.GoValidMarkerAlpha
}

// Init initializes the alpha validator factory.
func (a AlphaInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateAlpha
}
