// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// BooleanInitializer implements ValidatorInitializer for the boolean validator.
type BooleanInitializer struct{}

// Marker returns the marker identifier for the boolean validator.
func (b BooleanInitializer) Marker() string {
	return markers.GoValidMarkerBoolean
}

// Init initializes the boolean validator factory.
func (b BooleanInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateBoolean
}
