// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// ContainsanyInitializer implements ValidatorInitializer for the containsany validator.
type ContainsanyInitializer struct{}

// Marker returns the marker identifier for the containsany validator.
func (c ContainsanyInitializer) Marker() string {
	return markers.GoValidMarkerContainsany
}

// Init initializes the containsany validator factory.
func (c ContainsanyInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateContainsany
}
