// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// DateInitializer implements ValidatorInitializer for the date validator.
type DateInitializer struct{}

// Marker returns the marker identifier for the date validator.
func (d DateInitializer) Marker() string {
	return markers.GoValidMarkerDate
}

// Init initializes the date validator factory.
func (d DateInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateDate
}
