// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// EqInitializer implements ValidatorInitializer for the eq validator.
type EqInitializer struct{}

// Marker returns the marker identifier for the eq validator.
func (e EqInitializer) Marker() string {
	return markers.GoValidMarkerEq
}

// Init initializes the eq validator factory.
func (e EqInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateEq
}
