// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// Excluded_withInitializer implements ValidatorInitializer for the excluded_with validator.
type Excluded_withInitializer struct{}

// Marker returns the marker identifier for the excluded_with validator.
func (e Excluded_withInitializer) Marker() string {
	return markers.GoValidMarkerExcluded_with
}

// Init initializes the excluded_with validator factory.
func (e Excluded_withInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludedWith
}
