// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// Excluded_unlessInitializer implements ValidatorInitializer for the excluded_unless validator.
type Excluded_unlessInitializer struct{}

// Marker returns the marker identifier for the excluded_unless validator.
func (e Excluded_unlessInitializer) Marker() string {
	return markers.GoValidMarkerExcluded_unless
}

// Init initializes the excluded_unless validator factory.
func (e Excluded_unlessInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludedUnless
}
