// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// ExcludesallInitializer implements ValidatorInitializer for the excludesall validator.
type ExcludesallInitializer struct{}

// Marker returns the marker identifier for the excludesall validator.
func (e ExcludesallInitializer) Marker() string {
	return markers.GoValidMarkerExcludesall
}

// Init initializes the excludesall validator factory.
func (e ExcludesallInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludesall
}
