// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Excluded_withoutInitializer implements ValidatorInitializer for the excluded_without validator.
type Excluded_withoutInitializer struct{}

// Marker returns the marker identifier for the excluded_without validator.
func (e Excluded_withoutInitializer) Marker() string {
	return markers.GoValidMarkerExcluded_without
}

// Init initializes the excluded_without validator factory.
func (e Excluded_withoutInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludedWithout
}
