// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Excluded_without_allInitializer implements ValidatorInitializer for the excluded_without_all validator.
type Excluded_without_allInitializer struct{}

// Marker returns the marker identifier for the excluded_without_all validator.
func (e Excluded_without_allInitializer) Marker() string {
	return markers.GoValidMarkerExcluded_without_all
}

// Init initializes the excluded_without_all validator factory.
func (e Excluded_without_allInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateExcludedWithoutAll
}
