// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// FqdnInitializer implements ValidatorInitializer for the fqdn validator.
type FqdnInitializer struct{}

// Marker returns the marker identifier for the fqdn validator.
func (f FqdnInitializer) Marker() string {
	return markers.GoValidMarkerFqdn
}

// Init initializes the fqdn validator factory.
func (f FqdnInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateFQDN
}
