// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// GtInitializer implements ValidatorInitializer for the gt validator.
type GtInitializer struct{}

// Marker returns the marker identifier for the gt validator.
func (g GtInitializer) Marker() string {
	return markers.GoValidMarkerGt
}

// Init initializes the gt validator factory.
func (g GtInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateGT
}
