// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Ipv4Initializer implements ValidatorInitializer for the ipv4 validator.
type Ipv4Initializer struct{}

// Marker returns the marker identifier for the ipv4 validator.
func (i Ipv4Initializer) Marker() string {
	return markers.GoValidMarkerIpv4
}

// Init initializes the ipv4 validator factory.
func (i Ipv4Initializer) Init() registry.ValidatorFactory {
	return rules.ValidateIpv4
}
