// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Ipv6Initializer implements ValidatorInitializer for the ipv6 validator.
type Ipv6Initializer struct{}

// Marker returns the marker identifier for the ipv6 validator.
func (i Ipv6Initializer) Marker() string {
	return markers.GoValidMarkerIpv6
}

// Init initializes the ipv6 validator factory.
func (i Ipv6Initializer) Init() registry.ValidatorFactory {
	return rules.ValidateIpv6
}
