// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// IscolourInitializer implements ValidatorInitializer for the iscolour validator.
type IscolourInitializer struct{}

// Marker returns the marker identifier for the iscolour validator.
func (i IscolourInitializer) Marker() string {
	return markers.GoValidMarkerIscolour
}

// Init initializes the iscolour validator factory.
func (i IscolourInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateIscolour
}
