// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// IsdefaultInitializer implements ValidatorInitializer for the isdefault validator.
type IsdefaultInitializer struct{}

// Marker returns the marker identifier for the isdefault validator.
func (i IsdefaultInitializer) Marker() string {
	return markers.GoValidMarkerIsdefault
}

// Init initializes the isdefault validator factory.
func (i IsdefaultInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateIsdefault
}
