// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// LatitudeInitializer implements ValidatorInitializer for the latitude validator.
type LatitudeInitializer struct{}

// Marker returns the marker identifier for the latitude validator.
func (l LatitudeInitializer) Marker() string {
	return markers.GoValidMarkerLatitude
}

// Init initializes the latitude validator factory.
func (l LatitudeInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateLatitude
}
