// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// LongitudeInitializer implements ValidatorInitializer for the longitude validator.
type LongitudeInitializer struct{}

// Marker returns the marker identifier for the longitude validator.
func (l LongitudeInitializer) Marker() string {
	return markers.GoValidMarkerLongitude
}

// Init initializes the longitude validator factory.
func (l LongitudeInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateLongitude
}
