// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// LowercaseInitializer implements ValidatorInitializer for the lowercase validator.
type LowercaseInitializer struct{}

// Marker returns the marker identifier for the lowercase validator.
func (l LowercaseInitializer) Marker() string {
	return markers.GoValidMarkerLowercase
}

// Init initializes the lowercase validator factory.
func (l LowercaseInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateLowercase
}
