// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// MaxdurationInitializer implements ValidatorInitializer for the maxduration validator.
type MaxdurationInitializer struct{}

// Marker returns the marker identifier for the maxduration validator.
func (m MaxdurationInitializer) Marker() string {
	return markers.GoValidMarkerMaxduration
}

// Init initializes the maxduration validator factory.
func (m MaxdurationInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMaxduration
}
