// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// MinInitializer implements ValidatorInitializer for the min validator.
type MinInitializer struct{}

// Marker returns the marker identifier for the min validator.
func (m MinInitializer) Marker() string {
	return markers.GoValidMarkerMin
}

// Init initializes the min validator factory.
func (m MinInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateMin
}
