// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// NeInitializer implements ValidatorInitializer for the ne validator.
type NeInitializer struct{}

// Marker returns the marker identifier for the ne validator.
func (n NeInitializer) Marker() string {
	return markers.GoValidMarkerNe
}

// Init initializes the ne validator factory.
func (n NeInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateNe
}
