// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// NumberInitializer implements ValidatorInitializer for the number validator.
type NumberInitializer struct{}

// Marker returns the marker identifier for the number validator.
func (n NumberInitializer) Marker() string {
	return markers.GoValidMarkerNumber
}

// Init initializes the number validator factory.
func (n NumberInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateNumber
}
