// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// OneofInitializer implements ValidatorInitializer for the oneof validator.
type OneofInitializer struct{}

// Marker returns the marker identifier for the oneof validator.
func (o OneofInitializer) Marker() string {
	return markers.GoValidMarkerOneof
}

// Init initializes the oneof validator factory.
func (o OneofInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateOneof
}
