// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// RequiredInitializer implements ValidatorInitializer for the required validator.
type RequiredInitializer struct{}

// Marker returns the marker identifier for the required validator.
func (r RequiredInitializer) Marker() string {
	return markers.GoValidMarkerRequired
}

// Init initializes the required validator factory.
func (r RequiredInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequired
}
