// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Required_ifInitializer implements ValidatorInitializer for the required_if validator.
type Required_ifInitializer struct{}

// Marker returns the marker identifier for the required_if validator.
func (r Required_ifInitializer) Marker() string {
	return markers.GoValidMarkerRequired_if
}

// Init initializes the required_if validator factory.
func (r Required_ifInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequiredIf
}
