// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Required_withInitializer implements ValidatorInitializer for the required_with validator.
type Required_withInitializer struct{}

// Marker returns the marker identifier for the required_with validator.
func (r Required_withInitializer) Marker() string {
	return markers.GoValidMarkerRequired_with
}

// Init initializes the required_with validator factory.
func (r Required_withInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequired_with
}
