// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// Required_with_allInitializer implements ValidatorInitializer for the required_with_all validator.
type Required_with_allInitializer struct{}

// Marker returns the marker identifier for the required_with_all validator.
func (r Required_with_allInitializer) Marker() string {
	return markers.GoValidMarkerRequired_with_all
}

// Init initializes the required_with_all validator factory.
func (r Required_with_allInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequiredWithAll
}
