// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// Required_withoutInitializer implements ValidatorInitializer for the required_without validator.
type Required_withoutInitializer struct{}

// Marker returns the marker identifier for the required_without validator.
func (r Required_withoutInitializer) Marker() string {
	return markers.GoValidMarkerRequired_without
}

// Init initializes the required_without validator factory.
func (r Required_withoutInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateRequired_without
}
