// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/templatedop/govalid/internal/markers"
	"github.com/templatedop/govalid/internal/validator/registry"
	"github.com/templatedop/govalid/internal/validator/rules"
)

// UniqueInitializer implements ValidatorInitializer for the unique validator.
type UniqueInitializer struct{}

// Marker returns the marker identifier for the unique validator.
func (u UniqueInitializer) Marker() string {
	return markers.GoValidMarkerUnique
}

// Init initializes the unique validator factory.
func (u UniqueInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateUnique
}
