// Code generated by generate-validators; DO NOT EDIT.
package initializers

import (
	"github.com/sivchari/govalid/internal/markers"
	"github.com/sivchari/govalid/internal/validator/registry"
	"github.com/sivchari/govalid/internal/validator/rules"
)

// UriInitializer implements ValidatorInitializer for the uri validator.
type UriInitializer struct{}

// Marker returns the marker identifier for the uri validator.
func (u UriInitializer) Marker() string {
	return markers.GoValidMarkerUri
}

// Init initializes the uri validator factory.
func (u UriInitializer) Init() registry.ValidatorFactory {
	return rules.ValidateUri
}
